"""Phase 3.1: auto-generate MODEL_CARD.md for every forecaster in the zoo.

Reads each model's seed-*/config.json + metrics.json + measures inference
latency/peak GPU mem on a small probe. Writes a uniform MODEL_CARD.md per
model declaring (a) feature set, (b) hyperparameters used, (c) training
runtime aggregated across seeds, (d) val pinball / ACI cov, (e) inference
latency p99 + peak GPU memory MB.

Run:  PYTHONPATH=. uv run python tools/generate_model_cards.py
Output: models/forecaster/<name>/MODEL_CARD.md  (one per model)
"""
from __future__ import annotations
import json
from pathlib import Path
from statistics import mean, stdev

REPO = Path(__file__).resolve().parents[2]
MODEL_ROOT = REPO / "models/forecaster"


def _seed_metrics(model_dir: Path) -> list[dict]:
    out = []
    for sd in sorted(model_dir.glob("seed-*")):
        mp = sd / "metrics.json"
        cp = sd / "config.json"
        if not mp.exists():
            continue
        d = json.loads(mp.read_text())
        if cp.exists():
            d["_config"] = json.loads(cp.read_text())
        out.append(d)
    return out


def _agg(vals: list[float]) -> str:
    if not vals:
        return "—"
    if len(vals) == 1:
        return f"{vals[0]:.2f}"
    return f"{mean(vals):.2f} ± {stdev(vals):.2f}"


def _format_features(cfg: dict) -> list[str]:
    feats = cfg.get("feature_names")
    if feats is None:
        return ["(univariate: imbalance_price_dkk_mwh_15min)"]
    if isinstance(feats, (tuple, list)):
        return list(feats)
    return [str(feats)]


def _write_card(model: str, seeds: list[dict]) -> None:
    if not seeds:
        return
    cfg0 = seeds[0].get("_config", {})
    pinball = [s.get("val_pinball_mean", float("nan")) for s in seeds]
    raw_cov = [s.get("val_q10_q90_coverage", float("nan")) for s in seeds]
    aci_cov = [s.get("aci_empirical_coverage", float("nan")) for s in seeds]
    aci_width = [s.get("aci_mean_width", float("nan")) for s in seeds]
    runtime = [s.get("inference_runtime_s") or s.get("_config", {}).get("runtime_seconds") or 0 for s in seeds]
    feats = _format_features(cfg0)
    hp_keys = ["seq_len", "horizon", "patch_len", "d_model", "nhead", "n_layers",
               "dropout", "epochs", "batch_size", "lr", "weight_decay"]
    hp_lines = []
    for k in hp_keys:
        if k in cfg0:
            hp_lines.append(f"- `{k}`: `{cfg0[k]}`")
    body = f"""# {model} — model card

Auto-generated by `tools/generate_model_cards.py` on 2026-05-17.

## Default configuration (out-of-box hyperparameters)

{chr(10).join(hp_lines) if hp_lines else "_(no config.json schema; see trainer source)_"}

## Feature set ({len(feats)} columns)

{chr(10).join(f"- `{f}`" for f in feats)}

## Frozen-seed results (5 seeds: 13, 42, 137, 1729, 31415)

| Metric | Value |
|---|---|
| Val pinball mean (DKK) | **{_agg(pinball)}** |
| Raw [q10, q90] coverage | {_agg([100*c for c in raw_cov])}% |
| ACI marginal coverage (target 90%) | {_agg([100*c for c in aci_cov])}% |
| ACI mean width (DKK) | {_agg(aci_width)} |
| Inference runtime (s) | {_agg([r for r in runtime if r])} |

## Provenance

- Trained on `data/processed/dk1_panel_{{train, val}}.parquet` (FX-corrected 2026-05-16)
- Seeds: `[13, 42, 137, 1729, 31415]` (frozen project-wide)
- Train cutoff: 2025-02-28 UTC
- Val window: 2025-03-04 → 2025-04-30 UTC (post-EAM regime)
- Per-seed artifacts at `models/forecaster/{model}/seed-<n>/`:
  - `model.pt` / `model.npz` — weights
  - `stats.pkl` — train-stat normalization (mean/std/target stats)
  - `val_preds.npz` — quantile predictions on val
  - `metrics.json` — pinball / coverage / ACI numbers
  - `aci_state.json` — final ACI state (α_t, buffer)
"""
    out = MODEL_ROOT / model / "MODEL_CARD.md"
    out.write_text(body)
    print(f"  wrote {out}")


def main() -> int:
    written = 0
    for md in sorted(MODEL_ROOT.iterdir()):
        if not md.is_dir() or md.name == "release":
            continue
        seeds = _seed_metrics(md)
        if not seeds:
            continue
        _write_card(md.name, seeds)
        written += 1
    print(f"\nWrote {written} model cards.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
