name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
        with:
          version: "0.5.31"
      - name: Setup Python
        run: uv python install 3.12
      - name: uv sync
        run: uv sync --frozen
      - name: Build distribution
        run: uv build
      - name: GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*
          generate_release_notes: true
